### ISSUE TITLE
Нет автоостановки спама

### ISSUE THREAD

**Issue by nenavizhuniki** [rfoxxxyshit/raidbot#1]
Нет автооствновки бота -- если использовать его сразу в нескольких (или даже одной) беседах, то бот через некоторое время падает от перегрузки + срабатывет флуд-контроль на стороне ВК. Нужно добавить автопрекращение спама в беседе через некоторое время после начала рейда в ней. Тем не менее, это единственный и рабочий рейдбот на Github`е, и аналогов просто нету...

**Comment by rfoxxxy** [comment]
Сделаю в ближайшее свободное время
